### PR TITLE
JBPM-7477 - New docker image for full distribution

### PR DESCRIPTION
**Pull request by cristianonicolai**
Depends on https://github.com/kiegroup/kie-wb-distributions/pull/785

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@mbiarnes @mswiderski @bsremac  please take a look.

New image based on jBPM single zip distribution with tweak and examples to connect with different databases.

**Review by mswiderski — COMMENTED** [review]
@cristianonicolai looks really cool. What would be the procedure to get this running locally to test it?

**Comment by cristianonicolai** [comment]
@mswiderski just use the `./build.sh` script to build the image locally and then you can follow/check the instructions I added to the README file as this is how people will try it out once it is available on Docker Hub.

**Comment by mbiarnes** [comment]
@cristianonicolai looks good - I will close my PR that upgrades the existing files to 7.9.0.Final - so we prevent merge conflicts
I want Roger to see this :)

**Review by mbiarnes — APPROVED** [review]
+1 looks good. Should be also used for upgrading to 7.9.0.Final

**Review by mswiderski — APPROVED** [review]
just tested this and it works perfectly. Great job

**Pull request merged**
