### PR TITLE
upgraded to 7.18.0.Final

### PR DESCRIPTION
**Pull request by mbiarnes**
@cristianonicolai jBPM-Service repository of server doesn't run
Get a 404 - Error when accessing 
http://localhost:8088/repository

http://localhost:8088/business-central
http://localhost:8088/kie-server/docs
http://localhost:8088/jbpm-casemgmt 
work!

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@mbiarnes afaik, that is embedded now into BC, @mswiderski can you confirm that? We probably need to update docs reference to reflect that.

**Comment by mswiderski** [comment]
Correct, service task repo is now included in BC so the standalone was removed from single zip distribution

**Comment by romartin** [comment]
@mswiderski @cristianonicolai does it means we should change something on the docker images about it?

**Comment by mareknovotny** [comment]
@mbiarnes I guess so.

**Review by mareknovotny — DISMISSED** [review]
there is conflict now after merging PR with removing service repository war https://github.com/jboss-dockerfiles/jbpm/pull/56

**Comment by mswiderski** [comment]
@romartin I don’t think we need to change anything as it should be based on single zip distribution that is already updated

**Comment by cristianonicolai** [comment]
@romartin @mareknovotny I updated what was left in terms of docs on https://github.com/jboss-dockerfiles/jbpm/pull/56. This should be good to be merged once is rebased, as @mswiderski mentioned the changes in the dist were done at single zip dist already.

**Review by romartin — APPROVED** [review]
Ok thanks guys, it looks ready to me.

**Comment by cristianonicolai** [comment]
@mbiarnes this needs to be rebased now.

**Review by cristianonicolai — APPROVED** [review]

**Comment by mareknovotny** [comment]
I don't know how are you positioning in jbpm-workbench vs Business Central now after consolidation of BC and removing all *-workbench apps in favor of business-central, but I feel this is not consisten and we perhaps should change the naming of containers with respect to web context and real application name.

**Pull request merged**
